# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd5c7bbe035dad21490c3c0fd02ec5e8516d73397281bcc5736c70f07cb41b8bdd10b7ec2bd339e864dc5a67f8dbe60b7301b6a03689ca513e4a75d5a2553508

test:
  secret_key_base: 002e9cf715853a3d92fb1d2c09acfb36a25b858c7e6536d33d558516452adcedeca132131e00771a2892a188633f470e4549a1dcdef4cca36d92af14806b2104

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
